on: push
jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job push docker
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push image
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: user/app:latest